#pragma config(Sensor, S4,     ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     redButton,      sensorEV3_Touch)
#pragma config(Motor,  motorA,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          cups,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#define sensorFront S4

#include "config.c"
#include "position.c"
#include "movement.c"
#include "sonar.c"

task depliePince() {
	motor[cups] = -30;
	wait1Msec(500);
}

task repliePince() {
	motor[cups] = 30;
	wait1Msec(500);
}

task emergencyStop() {
	while (SensorValue[redButton] == 1) { wait1Msec(20); }
	stopAllTasks();
}

task main()
{

	while (SensorValue(redButton)==0) {
  	motor[motorRight] = 0;
  	motor[motorLeft] = 0;
  }

  startTask(emergencyStop);

  bool blueSide = true; // indique le côté du terrain d'où on commence, à modifier en fonction du match

  // Yellow : à droite si on a les manches à air devant
	wait1Msec(3000); // attente que le gros robot "Vérin" ait quitté le port

 	if(blueSide == true) {
    // blue side
	  motor[motorRight] = -30;
	  motor[motorLeft] = 0;
	  wait1Msec(500);
	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(1600);
	  motor[motorRight] = 0;
	  motor[motorLeft] = -30;
	  wait1Msec(3900);
	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(2000);

	  motor[motorRight] = 20;
	  motor[motorLeft] = -40;
	  wait1Msec(1900);
	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(2500);
	  motor[motorRight] = -30;
	  motor[motorLeft] = 0;
	  wait1Msec(1100);
	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(1250);

	  motor[motorRight] = -40;
	  motor[motorLeft] = 20;
	  wait1Msec(950);

	  motor[motorRight] = -30;
	  motor[motorLeft] = -25;
	  wait1Msec(3000);

	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(1800);

	  motor[motorRight] = 0;
	  motor[motorLeft] = 0;
	  startTask(repliePince);
	  wait1Msec(1000);

	  motor[motorRight] = 30;
	  motor[motorLeft] = 30;
	  wait1Msec(2000);

	  motor[motorRight] = -30;
	  motor[motorLeft] = 30;
	  wait1Msec(1000);

	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(2800);
	  motor[motorRight] = 30;
	  motor[motorLeft] = -30;
	  wait1Msec(1100);

	  motor[motorRight] = 0;
	  motor[motorLeft] = 0;
	  startTask(depliePince);
	  wait1Msec(1000);

	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(2200);
	}
	else {
		// yellow side

	  motor[motorRight] = 30;
	  motor[motorLeft] = -30;
	  wait1Msec(350);
	  motor[motorRight] = 0;
	  motor[motorLeft] = 0;
	  wait1Msec(500);
	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(2500);

		motor[motorRight] = 0;
	  motor[motorLeft] = -60;
	  wait1Msec(1600);
	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(2000);

	  motor[motorRight] = 20;
	  motor[motorLeft] = -40;
	  wait1Msec(1900);
	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(2500);
	  motor[motorRight] = -30;
	  motor[motorLeft] = 0;
	  wait1Msec(1100);
	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(1400);

	  motor[motorRight] = -40;
	  motor[motorLeft] = 20;
	  wait1Msec(950);

	  motor[motorRight] = -30;
	  motor[motorLeft] = -25;
	  wait1Msec(3000);

	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(1800);

	  motor[motorRight] = 0;
	  motor[motorLeft] = 0;
	  startTask(repliePince);
	  wait1Msec(1000);

	  motor[motorRight] = 30;
	  motor[motorLeft] = 30;
	  wait1Msec(2000);

	  motor[motorRight] = -30;
	  motor[motorLeft] = 30;
	  wait1Msec(1000);

	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(2800);
	  motor[motorRight] = 30;
	  motor[motorLeft] = -30;
	  wait1Msec(1100);

	  motor[motorRight] = 0;
	  motor[motorLeft] = 0;
	  startTask(depliePince);
	  wait1Msec(1000);

	  motor[motorRight] = -30;
	  motor[motorLeft] = -30;
	  wait1Msec(2100);

	}

}
